### ISSUE TITLE
CI Server

### ISSUE THREAD

**Issue by tevert** [MediaComplete/MediaComplete#24]
Possibly look at switch our CI server to use Jenkins with MSBuild plugin instead of CCNet, sounds like it might be easier to utilize/setup and will help with better automation possibilities and might remove the erroneous GIT emails...

**Comment by tevert** [comment]
Arjun set up Travis CI; it's breaking because Mono doesn't support WPF. Fortunately, none of our automated tests need the WPF frontend, so we should be able to have it only build the backend chunk. Only potential issue then is that we can't have the CI automatically publish new releases, but we can tackle that later.

**Comment by shankera** [comment]
Ohhhh THATS why its breaking!  Literally didnt even consider that wpf wasnt supported. The problem right now, then is that we point the build at the .sln, and it builds the whole thing. This might be the reason we needed to pull the lib/tests into their own repo.

**Comment by tevert** [comment]
Should all good now. Arjun, please verify and let me know if you think something is missing. 
- CI only builds Lib and Test projects.
- Tests were all converted to NUnit tests, since MSTest isn't supported by mono.
- Cleaned up YML to remove some redundant steps.
- Added "sudo: false" per Travis's request that we move to a containerized build.
- Verified that failing tests will fail the build.
- Fixed the badge on the README to link to the CI page instead of just the badge image. 
- Opened issue #111 since some of our tests are causing the Logger to vomit all over our build.
