### ISSUE TITLE
As a stupid user, I would like to not inadvertently perform duplicate imports

### ISSUE THREAD

**Issue by tevert** [MediaComplete/MediaComplete#47]
My concern would be if I had 1000 files to import, and there was a greater than 10 second delay, I might, as a stupid user, decide that feature was broken and then want to manually copy files into our music directory instead. We should prevent or collapse the multiple imports.

**Comment by shankera** [comment]
https://github.com/MediaComplete/MediaComplete.Lib/issues/17
