### ISSUE TITLE
Add/remove Youtube songs to library

### ISSUE THREAD

**Issue by tevert** [MediaComplete/MediaComplete#61]
- Allowing adding Youtube songs into your local library by context menu clicking on search results. 
- Playing a song from Youtube automatically includes it in your library 
  -- Provide a setting to disable this 
- You can delete Youtube songs from your library via context menu. 
- Youtube songs are stored using some lightweight local persistence mechanism.

**Comment by shankera** [comment]
https://github.com/MediaComplete/MediaComplete.Lib/issues/10
