### ISSUE TITLE
As a user, I would like to undo file deletion, so I can recover erroneously deleted files.

### ISSUE THREAD

**Issue by tevert** [MediaComplete/MediaComplete#74]
- When a file is "deleted", it is actually moved to a temporary directory. 
- An undo option is available on the toolbar to add these files back into the library. 
- When the application starts up (or gracefully shuts down), it moves files in the temporary directory to the Windows recycle bin.

**Comment by shankera** [comment]
https://github.com/MediaComplete/MediaComplete.Lib/issues/8
