### ISSUE TITLE
Index local files

### ISSUE THREAD

**Issue by tevert** [MediaComplete/MediaComplete#77]
- Use our standard list of metadata attributes for field values and the file location.
- Library will most likely be Lucene.NET (3.0.3). 30 minutes of research to verify.
- Luke can be used to manually verify the index. (http://www.getopt.org/luke/)
- Index rebuilds will be triggered by filewatcher events and on application start.

**Comment by shankera** [comment]
https://github.com/MediaComplete/MediaComplete.Lib/issues/6
