### ISSUE TITLE
Introduce a dependency injection library

### ISSUE THREAD

**Issue by shankera** [MediaComplete/MediaComplete#82]
lots of dependencies being manually managed, not the best way to do it.

**Comment by shankera** [comment]
https://github.com/roboguice/roboguice

**Comment by tevert** [comment]
We're already using AutoFac, would Roboguice make it better?

https://github.com/MediaComplete/MediaComplete/blob/development/MSOE.MediaComplete/MainWindow.xaml.cs#L87

**Comment by shankera** [comment]
forgot to assign myself to this btw

roboguice actually doesnt exist for c# it was just something to look into.

I've actually been looking at ninject. it seems more popular than autofac, but less optimized too.

**Comment by shankera** [comment]
Yup, good call. Autofac looks like it'll do the trick

**Comment by shankera** [comment]
As a note, we lose some of our 'idiot proofing' that we had when this was initially developed, from when we just had a ton of singletons.
