### ISSUE TITLE
Update Read Me

### ISSUE THREAD

**Issue by TorrhenStark** [MediaComplete/MediaComplete#83]
Hi,

It looks like the Read Me for this project is using a default template of some type and contains no information specific to MediaComplete. Can this be updated? I am not too familiar with the project, otherwise I would issue a PR. 

Here are a couple projects that have a really good Read Me to draw inspiration from:

https://github.com/dotnet/roslyn

https://github.com/scriptcs/scriptcs

https://github.com/NancyFx/Nancy

**Comment by shankera** [comment]
Hey, sorry about that. I will have it updated this evening. In the meantime you can find some preliminary information at mediacomplete.github.io

Sorry again!
Arjun

**Comment by TorrhenStark** [comment]
No worries. I didn't see the URL before but that's helpful.

**Comment by shankera** [comment]
I've updated the readme here https://github.com/MediaComplete/MediaComplete/tree/readme

If you see any room for improvement, please don't hesitate to give a suggestion!
